name: writer-cps-mtl
version: 0.1.1.4
synopsis: MonadWriter orphan instances for writer-cps-transformers
description:
  The WriterT and RWST monad transformers provided by writer-cps-transformers
  are written in continuation passing style and avoid the space-leak
  problem of the traditional Control.Monad.Trans.Writer.Strict and Control.Monad.Trans.Writer.Lazy.
  See also (<http://hackage.haskell.org/package/writer-cps-transformers>).
category: Control
author: Andy Gill, Edward Kmett, Daniel Mendler
maintainer: mail@daniel-mendler.de
copyright: 2016 Daniel Mendler
license: BSD3
github: minad/writer-cps-mtl

ghc-options:
- -Wall

dependencies:
- base < 6
- transformers >= 0.4 && < 0.6
- mtl >= 2.2 && < 2.4
- writer-cps-transformers >= 0.1.1.1 && < 0.3

tested-with:
  GHC == 7.0.4,
  GHC == 7.2.2,
  GHC == 7.4.2,
  GHC == 7.6.3,
  GHC == 7.8.4,
  GHC == 7.10.3,
  GHC == 8.0.1

library:
  source-dirs: src
